name: Keep Render Awake

on:
  schedule:
    - cron: "*/15 * * * *"  # a cada 15 minutos
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          curl -s https://pdf-translator-02hl.onrender.com/ > /dev/null
